WritersClub.Solution/WritersClub/Models/Issue.cs
using System.Collections.Generic;

namespace WritersClub.Models
{
  public class Issue
  {
    public Issue()
    {
      this.Entries = new HashSet<Entry>();
    }

    public int IssueId { get; set; }
    public string Prompt { get; set; }
    public int JournalId { get; set; }
    public virtual Journal Journal { get; set; }

    // public string UserId { get; set;} // this is the prompt author...
    public virtual ICollection<Entry> Entries { get; set; }
  }
}

WritersClub.Solution/WritersClub/Controllers/EntriesController.cs
using Microsoft.AspNetCore.Mvc;
using WritersClub.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace WritersClub.Controllers
{
  [Authorize]
  public class EntriesController : Controller
  {
    private readonly WritersClubContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public EntriesController(UserManager<ApplicationUser> userManager, WritersClubContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public async Task<ActionResult> Index()
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var userEntries = _db.Entries.Where(entry => entry.User.Id == currentUser.Id);
      return View(userEntries);
    }

    public ActionResult Create()
    {
      ViewBag.IssueId = new SelectList(_db.Issues, "IssueId", "Prompt");
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Entry entry)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      entry.User = currentUser;
      _db.Entries.Add(entry);
      _db.SaveChanges();

      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Entry thisEntry = _db.Entries
        .Include(entry => entry.User)
        .Include(entry => entry.Issue)
        .FirstOrDefault(entries => entries.EntryId == id);
      return View(thisEntry);
    }

    public ActionResult Edit(int id)
    {
      var thisEntry = _db.Entries.FirstOrDefault(entries => entries.EntryId == id);
      ViewBag.IssueId = new SelectList(_db.Issues, "IssueId", "Prompt");
      return View(thisEntry);
    }

    [HttpPost]
    public ActionResult Edit(Entry entry)
    {
      _db.Entry(entry).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisEntry = _db.Entries.FirstOrDefault(entries => entries.EntryId == id);
      return View(thisEntry);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisEntry = _db.Entries.FirstOrDefault(entries => entries.EntryId == id);
      _db.Entries.Remove(thisEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

WritersClub.Solution/WritersClub/Controllers/IssuesController.cs
using Microsoft.AspNetCore.Mvc;
using WritersClub.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace WritersClub.Controllers
{
  public class IssuesController : Controller
  {

    private readonly WritersClubContext _db;

    public IssuesController(WritersClubContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Issue> model = _db.Issues.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.JournalId = new SelectList(_db.Journals, "JournalId", "JournalName");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Issue issue)
    {
      _db.Issues.Add(issue);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Issue thisIssue = _db.Issues
        .Include(issue => issue.Entries)
        .Include(issue => issue.Journal)
        .FirstOrDefault(issue => issue.IssueId == id);
      // thisIssue.Items = _db.Items.Where(item => item.IssueId == id).ToList();
      return View(thisIssue);
    }

    public ActionResult Edit(int id)
    {
      var thisIssue = _db.Issues.FirstOrDefault(issues => issues.IssueId == id);
      return View(thisIssue);
    }

    [HttpPost]
    public ActionResult Edit(Issue issue)
    {
      _db.Entry(issue).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisIssue = _db.Issues.FirstOrDefault(issues => issues.IssueId == id);
      return View(thisIssue);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisIssue = _db.Issues.FirstOrDefault(issues => issues.IssueId == id);
      _db.Issues.Remove(thisIssue);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

WritersClub.Solution/WritersClub/Views/Issues/Create.cshtml
@{
  Layout = "_Layout";
}

@model WritersClub.Models.Issue

<h4>Add a new Issue</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Prompt)
  @Html.TextAreaFor(model => model.Prompt)

  @Html.LabelFor(model => model.JournalId)
  @Html.DropDownList("JournalId")

  <input type="submit" value="Create new issue" />
}
<p>@Html.ActionLink("Back to Issues", "Index")</p>

WritersClub.Solution/WritersClub/Views/Issues/Delete.cshtml
@{
  Layout = "_Layout";
}

@model WritersClub.Models.Issue

<h2>Are you sure you want to delete this Issue?</h2>


@Html.DisplayNameFor(model => model.Prompt): @Html.DisplayFor(model => model.Prompt)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Cancel", "Index")

WritersClub.Solution/WritersClub/Views/Issues/Details.cshtml
@{
    Layout = "_Layout";
}

@using WritersClub.Models;
@model WritersClub.Models.Issue;

<h2>Issue @Html.DisplayFor(model => model.IssueId) Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Prompt): @Html.DisplayFor(model => model.Prompt)</h3>

<ul>
    @if (@Model.Entries.Count == 0)
    {
        <p>no entries yet</p>
    }

    @foreach (var entry in @Model.Entries)
    {
        <li>@Html.ActionLink($"{entry.Title}", "Details", "Entries", new { id = entry.EntryId })</li>
    }
</ul>

<p>@Html.ActionLink("Back to list of Issues", "Index")</p>
<p>@Html.ActionLink("Edit Issue", "Edit", new { id = Model.IssueId })</p>
<p>@Html.ActionLink("Delete Issue", "Delete", new { id = Model.IssueId })</p>

WritersClub.Solution/WritersClub/Views/Issues/Edit.cshtml
@{
  Layout = "_Layout";
}

@model WritersClub.Models.Issue

<h2>Edit</h2>

@* <h4>Edit the name of this issue: @Html.DisplayFor(model => model.Title)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.IssueId)

    @Html.LabelFor(model => model.Title)
    @Html.EditorFor(model => model.Title)

    <input type="submit" value="Save" />
} *@

<p>@Html.ActionLink("Cancel", "Index")</p>

WritersClub.Solution/WritersClub/Views/Issues/Index.cshtml
@{
  Layout = "_Layout";
}

@using WritersClub.Models;
@model List<WritersClub.Models.Issue>;

<h1>Issues</h1>

<ul>
  @foreach(Issue issue in Model)
  {
      <li>@Html.ActionLink($"{issue.Prompt}", "Details", new { id = issue.IssueId })</li>
  }
</ul>

<p>@Html.ActionLink("Add new issue", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>