WritersClub.Solution/WritersClub/Models/Entry.cs
using System.Collections.Generic;
using System;

namespace WritersClub.Models
{
  public class Entry
  {
    public string Title { get; set; }
    public int EntryId { get; set; }
    public int IssueId { get; set; }
    public virtual Issue Issue { get; set; }
    public string Content { get; set; }
    public DateTime Timestamp { get; set; }
    public int UserId { get; set; }
    public virtual ApplicationUser User { get; set; }
  }
}

WritersClub.Solution/WritersClub/Controllers/EntriesController.cs
using Microsoft.AspNetCore.Mvc;
using WritersClub.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace WritersClub.Controllers
{
  [Authorize]
  public class EntriesController : Controller
  {
    private readonly WritersClubContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public EntriesController(UserManager<ApplicationUser> userManager, WritersClubContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public async Task<ActionResult> Index()
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var userEntries = _db.Entries.Where(entry => entry.User.Id == currentUser.Id);
      return View(userEntries);
    }

    public ActionResult Create()
    {
      ViewBag.IssueId = new SelectList(_db.Issues, "IssueId", "Prompt");
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Entry entry)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      entry.User = currentUser;
      _db.Entries.Add(entry);
      _db.SaveChanges();

      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Entry thisEntry = _db.Entries
        .Include(entry => entry.User)
        .Include(entry => entry.Issue)
        .FirstOrDefault(entries => entries.EntryId == id);
      return View(thisEntry);
    }

    public ActionResult Edit(int id)
    {
      var thisEntry = _db.Entries.FirstOrDefault(entries => entries.EntryId == id);
      ViewBag.IssueId = new SelectList(_db.Issues, "IssueId", "Prompt");
      return View(thisEntry);
    }

    [HttpPost]
    public ActionResult Edit(Entry entry)
    {
      _db.Entry(entry).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisEntry = _db.Entries.FirstOrDefault(entries => entries.EntryId == id);
      return View(thisEntry);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisEntry = _db.Entries.FirstOrDefault(entries => entries.EntryId == id);
      _db.Entries.Remove(thisEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

WritersClub.Solution/WritersClub/Controllers/IssuesController.cs
using Microsoft.AspNetCore.Mvc;
using WritersClub.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace WritersClub.Controllers
{
  public class IssuesController : Controller
  {

    private readonly WritersClubContext _db;

    public IssuesController(WritersClubContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Issue> model = _db.Issues.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.JournalId = new SelectList(_db.Journals, "JournalId", "JournalName");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Issue issue)
    {
      _db.Issues.Add(issue);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Issue thisIssue = _db.Issues
        .Include(issue => issue.Entries)
        .Include(issue => issue.Journal)
        .FirstOrDefault(issue => issue.IssueId == id);
      // thisIssue.Items = _db.Items.Where(item => item.IssueId == id).ToList();
      return View(thisIssue);
    }

    public ActionResult Edit(int id)
    {
      var thisIssue = _db.Issues.FirstOrDefault(issues => issues.IssueId == id);
      return View(thisIssue);
    }

    [HttpPost]
    public ActionResult Edit(Issue issue)
    {
      _db.Entry(issue).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisIssue = _db.Issues.FirstOrDefault(issues => issues.IssueId == id);
      return View(thisIssue);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisIssue = _db.Issues.FirstOrDefault(issues => issues.IssueId == id);
      _db.Issues.Remove(thisIssue);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

WritersClub.Solution/WritersClub/Views/Entries/Create.cshtml
@{
  Layout = "_Layout";
}

@model WritersClub.Models.Entry

<h4>Create New Entry</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Title)
  @Html.TextBoxFor(model => model.Title)

  @Html.LabelFor(model => model.Content)
  @Html.TextAreaFor(model => model.Content)

  <input type="hidden" value="@DateTime.Now" name="Timestamp">

  @Html.Label("Select Prompt")
  @Html.DropDownList("IssueId")
  <input type="submit" value="Add this entry" class="btn btn-default"/>
}
<p class="btn btn-default">@Html.ActionLink("Back", "Index")</p>

WritersClub.Solution/WritersClub/Views/Entries/Delete.cshtml
@{
  Layout = "_Layout";
}

@model WritersClub.Models.Entry

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Title): @Html.DisplayFor(model => model.Title)
@using (Html.BeginForm())
{
    <input class="btn btn-default" type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

WritersClub.Solution/WritersClub/Views/Entries/Details.cshtml
  @{
    Layout = "_Layout";
}

@using System.Security.Claims
@using WritersClub.Models
@model WritersClub.Models.Entry

<h2>Entry Details</h2>

<hr />

<h4>@Html.DisplayNameFor(model => model.Issue.Prompt): @Html.DisplayFor(model => model.Issue.Prompt)</h4>

<hr>

<h5>Issue No. @Html.DisplayFor(model => model.IssueId)</h5> 
<h3>@Html.DisplayFor(model => model.Title)</h3>
<h5>By @Html.DisplayFor(model => model.User.UserName) on @Html.DisplayFor(model => model.Timestamp)</h5> 
<p>@Html.DisplayFor(model => model.Content)</p>
<hr>

<p>@Html.ActionLink("See more of user's entries", "Index")</p>
<p>@Html.ActionLink("See more of this issue's details", "Details", "Issues", new { id = Model.Issue.IssueId})</p>
<p>@Html.ActionLink("Edit Entry", "Edit", new { id = Model.EntryId })</p>
<p>@Html.ActionLink("Delete Entry", "Delete", new { id = Model.EntryId })</p> 

WritersClub.Solution/WritersClub/Views/Entries/Edit.cshtml
@{
  Layout = "_Layout";
}

@model WritersClub.Models.Entry

<h2>Edit</h2>

<h4>Edit this journal entry: @Html.DisplayFor(model => model.Title)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.EntryId)

    @Html.HiddenFor(model => model.Timestamp)

    @Html.LabelFor(model => model.Title)
    @Html.EditorFor(model => model.Title)

    @Html.LabelFor(model => model.Content)
    @Html.TextAreaFor(model => model.Content)
    
    @Html.Label("Select Issue")
    @Html.DropDownList("IssueId")
    
    <input class="btn btn-default" type="submit" value="Save" />
}
<p>@Html.ActionLink("Cancel", "Index")</p>

WritersClub.Solution/WritersClub/Views/Entries/Index.cshtml
@{
  Layout = "_Layout";
}

@using WritersClub.Models;
@model IEnumerable<WritersClub.Models.Entry>;

<h1>Entries for @User.Identity.Name</h1>
<h1>Entries Index</h1>

@if (@Model.Any())
{
  <ul>
    @foreach(Entry entry in Model)
    {
        <li>@Html.ActionLink($"{entry.Title}", "Details", new { id = entry.EntryId })</li>
    }
  </ul>
} 
else
{
  <h3>No entries have been added yet!</h3>
}

<p>@Html.ActionLink("Add new entry", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

----------------------------------------------------------------

@* @using ToDoList.Models;
@model List<ToDoList.Models.Item>;

<h1>Items</h1>

@if (@Model.Count == 0)
{
  <h3>No Entries have been added yet!</h3>
} 

<ul>
  @foreach(Item item in Model)
  {
      <li>@Html.ActionLink($"{item.Description}", "Details", new { id = item.ItemId }) | @item.Category.Name</li>
  }
</ul> *@